import os

MAIL_SERVER = 'live.smtp.mailtrap.io'
MAIL_PORT = 587
MAIL_USE_TLS = True
MAIL_USE_SSL = False
MAIL_USERNAME = os.getenv('MAIL_USERNAME')
MAIL_PASSWORD = os.getenv('MAIL_PASSWORD')
RECAPTCHA_SECRET_KEY = os.getenv('RECAPTCHA_SECRET_KEY')